version: '3'
services:

  bill:
    image: bill:latest
    container_name: bill
    volumes:
      - ./db/:/app/db/
      - ./py:/app/py/
    ports:
      - "6060:6060"
#    command: python3 /app/py/app.py
#    command: tail -20f /dev/null

  bill2:
    image: msqqcq/billing-hxq:1.0
    container_name: bill2
    ports:
      - "6060:6060"